import type { CardId, CardRole, CardTier, CardTiming } from "./types";

export type CardDefinition = {
  id: CardId;
  role: CardRole;
  name: string;
  timing: CardTiming;
  tier: CardTier;
  copies: number;
  description: string;
};

export const CARD_DEFINITIONS: Record<CardId, CardDefinition> = {
  HBP: {
    id: "HBP",
    role: "offense",
    name: "몸에 맞는 공",
    timing: "after_pitch",
    tier: "basic",
    copies: 2,
    description: "볼 판정을 대신해 타자가 출루하고 강제주자가 진루합니다.",
  },
  WP: {
    id: "WP",
    role: "offense",
    name: "폭투",
    timing: "after_pitch",
    tier: "basic",
    copies: 3,
    description: "모든 주자가 한 베이스 진루한 뒤 원래 볼 판정을 처리합니다.",
  },
  BK: {
    id: "BK",
    role: "offense",
    name: "보크",
    timing: "before_pitch",
    tier: "basic",
    copies: 2,
    description: "투구 전에 모든 주자가 한 베이스 진루합니다.",
  },
  POE: {
    id: "POE",
    role: "offense",
    name: "견제 송구 실책",
    timing: "before_pitch",
    tier: "basic",
    copies: 2,
    description: "견제사를 무효로 하고 모든 주자가 한 베이스 진루합니다.",
  },
  SB2: {
    id: "SB2",
    role: "offense",
    name: "2루 도루",
    timing: "after_pitch",
    tier: "basic",
    copies: 5,
    description: "1루 주자가 2루 도루를 시도합니다.",
  },
  SB3: {
    id: "SB3",
    role: "offense",
    name: "3루 도루",
    timing: "after_pitch",
    tier: "basic",
    copies: 4,
    description: "2루 주자가 3루 도루를 시도합니다.",
  },
  SBH: {
    id: "SBH",
    role: "offense",
    name: "홈 도루",
    timing: "after_pitch",
    tier: "intermediate",
    copies: 1,
    description: "3루 주자가 홈 도루를 시도합니다.",
  },
  SB: {
    id: "SB",
    role: "offense",
    name: "희생번트",
    timing: "after_contact",
    tier: "intermediate",
    copies: 4,
    description: "타자는 아웃되고 모든 주자가 한 베이스 진루합니다.",
  },
  SQ1: {
    id: "SQ1",
    role: "offense",
    name: "스퀴즈 번트",
    timing: "after_contact",
    tier: "intermediate",
    copies: 3,
    description: "3루 주자는 득점하고 타자는 아웃됩니다.",
  },
  SQ2: {
    id: "SQ2",
    role: "offense",
    name: "기습 스퀴즈",
    timing: "after_contact",
    tier: "intermediate",
    copies: 2,
    description: "3루 주자가 득점하고 타자도 1루에 살아갑니다.",
  },
  E: {
    id: "E",
    role: "offense",
    name: "수비 실책",
    timing: "after_batting",
    tier: "intermediate",
    copies: 2,
    description: "타자와 모든 주자가 한 베이스 안전 진루합니다.",
  },
  "1H1E": {
    id: "1H1E",
    role: "offense",
    name: "원히트 원에러",
    timing: "after_hit",
    tier: "intermediate",
    copies: 1,
    description: "안타 진루 뒤 기존 주자들이 한 베이스 더 진루합니다.",
  },
  HRC: {
    id: "HRC",
    role: "offense",
    name: "중월 홈런",
    timing: "after_batting",
    tier: "intermediate",
    copies: 2,
    description: "홈런을 확정합니다.",
  },
  HNR: {
    id: "HNR",
    role: "offense",
    name: "히트 앤드 런",
    timing: "before_pitch",
    tier: "advanced",
    copies: 2,
    description: "컨택을 확정하고 타구에 따라 주자에게 특수 진루를 적용합니다.",
  },
  RNH: {
    id: "RNH",
    role: "offense",
    name: "런 앤드 히트",
    timing: "before_pitch",
    tier: "advanced",
    copies: 1,
    description: "3볼에서 주자가 먼저 출발하고 컨택 시 특수 진루를 적용합니다.",
  },
  SNO: {
    id: "SNO",
    role: "offense",
    name: "스트라이크아웃 낫아웃",
    timing: "after_pitch",
    tier: "advanced",
    copies: 2,
    description: "세 번째 헛스윙을 낫아웃으로 바꿔 타자와 주자를 진루시킵니다.",
  },
  CIB: {
    id: "CIB",
    role: "offense",
    name: "포수 타격방해",
    timing: "after_pitch",
    tier: "advanced",
    copies: 1,
    description: "헛스윙 판정을 타자 출루로 바꿉니다.",
  },
  IOB: {
    id: "IOB",
    role: "offense",
    name: "야수 주루방해",
    timing: "after_batting",
    tier: "advanced",
    copies: 1,
    description: "타자와 강제주자에게 한 베이스 안전진루권을 줍니다.",
  },
  CS2: {
    id: "CS2",
    role: "defense",
    name: "2루 도루 저지",
    timing: "after_pitch",
    tier: "basic",
    copies: 3,
    description: "2루 도루를 시도한 주자를 아웃시킵니다.",
  },
  CS3: {
    id: "CS3",
    role: "defense",
    name: "3루 도루 저지",
    timing: "after_pitch",
    tier: "basic",
    copies: 3,
    description: "3루 도루를 시도한 주자를 아웃시킵니다.",
  },
  CSH: {
    id: "CSH",
    role: "defense",
    name: "홈 도루 저지",
    timing: "after_pitch",
    tier: "basic",
    copies: 1,
    description: "홈 도루를 시도한 주자를 아웃시킵니다.",
  },
  GDP: {
    id: "GDP",
    role: "defense",
    name: "땅볼 병살",
    timing: "after_batting",
    tier: "basic",
    copies: 3,
    description: "가장 앞선 강제주자와 타자를 아웃시킵니다.",
  },
  PO1: {
    id: "PO1",
    role: "defense",
    name: "1루 견제",
    timing: "before_pitch",
    tier: "basic",
    copies: 3,
    description: "투구 전에 1루 주자를 견제 아웃시킵니다.",
  },
  PO2: {
    id: "PO2",
    role: "defense",
    name: "2루 견제",
    timing: "before_pitch",
    tier: "basic",
    copies: 2,
    description: "투구 전에 2루 주자를 견제 아웃시킵니다.",
  },
  BD: {
    id: "BD",
    role: "defense",
    name: "번트 수비",
    timing: "after_contact",
    tier: "intermediate",
    copies: 3,
    description: "희생번트의 선행주자를 아웃시키고 타자를 1루에 둡니다.",
  },
  GBH: {
    id: "GBH",
    role: "defense",
    name: "주자 묶어두기",
    timing: "after_batting",
    tier: "intermediate",
    copies: 3,
    description: "GA에서 주자를 묶어두고 타자만 아웃시킵니다.",
  },
  GTP: {
    id: "GTP",
    role: "defense",
    name: "땅볼 삼중살",
    timing: "after_batting",
    tier: "intermediate",
    copies: 1,
    description: "두 명의 강제주자와 타자를 아웃시켜 삼중살을 완성합니다.",
  },
  LDP: {
    id: "LDP",
    role: "defense",
    name: "직선타 병살",
    timing: "after_batting",
    tier: "intermediate",
    copies: 1,
    description: "안타성 직선타를 잡고 가장 앞선 주자까지 아웃시킵니다.",
  },
  A2: {
    id: "A2",
    role: "defense",
    name: "2루 보살",
    timing: "after_hit",
    tier: "intermediate",
    copies: 2,
    description: "2루타를 친 타자주자를 2루에서 아웃시킵니다.",
  },
  A3H: {
    id: "A3H",
    role: "defense",
    name: "3루 보살",
    timing: "after_hit",
    tier: "intermediate",
    copies: 2,
    description: "1루에서 3루를 노린 주자를 3루에서 아웃시킵니다.",
  },
  AHH: {
    id: "AHH",
    role: "defense",
    name: "홈 보살",
    timing: "after_hit",
    tier: "intermediate",
    copies: 2,
    description: "2루에서 홈을 노린 주자를 홈에서 아웃시킵니다.",
  },
  A3F: {
    id: "A3F",
    role: "defense",
    name: "희생플라이 3루 보살",
    timing: "after_batting",
    tier: "intermediate",
    copies: 2,
    description: "태그업으로 3루를 노린 2루 주자를 아웃시킵니다.",
  },
  AHF: {
    id: "AHF",
    role: "defense",
    name: "희생플라이 홈 보살",
    timing: "after_batting",
    tier: "intermediate",
    copies: 2,
    description: "태그업으로 홈을 노린 3루 주자를 아웃시킵니다.",
  },
  IFD: {
    id: "IFD",
    role: "defense",
    name: "내야 뜬공 병살",
    timing: "after_batting",
    tier: "advanced",
    copies: 1,
    description:
      "인필드플라이가 아닌 내야 뜬공에서 1루 주자와 타자를 아웃시킵니다.",
  },
  CO1: {
    id: "CO1",
    role: "defense",
    name: "포수 1루 견제",
    timing: "after_pitch",
    tier: "advanced",
    copies: 2,
    description: "투구 직후 포수가 1루 주자를 견제 아웃시킵니다.",
  },
  CO3: {
    id: "CO3",
    role: "defense",
    name: "포수 3루 견제",
    timing: "after_pitch",
    tier: "advanced",
    copies: 1,
    description: "투구 직후 포수가 3루 주자를 견제 아웃시킵니다.",
  },
  FFO: {
    id: "FFO",
    role: "defense",
    name: "파울 플라이 아웃",
    timing: "after_pitch",
    tier: "advanced",
    copies: 2,
    description: "파울 타구를 잡아 타자를 아웃시킵니다.",
  },
  RHB: {
    id: "RHB",
    role: "defense",
    name: "타구에 맞은 주자",
    timing: "after_batting",
    tier: "advanced",
    copies: 1,
    description: "땅볼에 맞은 가장 앞선 주자를 아웃시키고 타자는 1루에 둡니다.",
  },
};

export const CARD_DECK_COUNTS = {
  offense: [
    "HBP",
    "WP",
    "BK",
    "POE",
    "SB2",
    "SB3",
    "SBH",
    "SB",
    "SQ1",
    "SQ2",
    "E",
    "1H1E",
    "HRC",
    "HNR",
    "RNH",
    "SNO",
    "CIB",
    "IOB",
  ],
  defense: [
    "CS2",
    "CS3",
    "CSH",
    "GDP",
    "PO1",
    "PO2",
    "BD",
    "GBH",
    "GTP",
    "LDP",
    "A2",
    "A3H",
    "AHH",
    "A3F",
    "AHF",
    "IFD",
    "CO1",
    "CO3",
    "FFO",
    "RHB",
  ],
} as const satisfies Record<CardRole, readonly CardId[]>;
